[build]
  publish = "."

[[redirects]]
  from = "/device/:id"
  to = "/device.html?item=:id"
  status = 200
  force = true

[[redirects]]
  from = "/device/:id/*"
  to = "/device.html?item=:id"
  status = 200
  force = true

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
